name: Monday build
on:
  schedule:
    # Every Monday @ 5am (UTC + 1)
    - cron: '9 7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Monday build webhook
        run: curl -s -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_MONDAY_BUILD_HOOK }}
