name: Monday build
on:
  schedule:
    # Every Monday @ 5am (UTC + 1)
<<<<<<< HEAD
    - cron: '20 7 * * *'

=======
    - cron: '9 7 * * *'
>>>>>>> 25f313b0be7a540b10501fd7a792185c98dc4310
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - name: Trigger Netlify' Monday build webhook
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5fd3c0cb284e7636ae6a71b8
=======
      - name: Trigger Netlify Monday build webhook
        run: curl -s -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_MONDAY_BUILD_HOOK }}
>>>>>>> 25f313b0be7a540b10501fd7a792185c98dc4310
