name: Monday build
on:
  schedule:
    # Every Monday @ 5am (UTC + 1)
    - cron: '22 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify' Monday build webhook
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5fd3c0cb284e7636ae6a71b8
