name: Wednesday build
on:
  schedule:
    # Every Wednesday @ 5am — Bugada
    - cron: '0 4 * * 3'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Monday build webhook
        run: curl -X POST -d {} "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_MONDAY_BUILD_HOOK }}
